import { existsSync, readFileSync } from 'node:fs'
import { extname, join } from 'node:path'
import { err, type FridayError, fridayError, ok, type Result } from '@friday/contracts'
import { parse as parseToml } from 'smol-toml'
import { type DeepPartialConfig, expandPath } from './defaults.js'

/**
 * The configuration file layer.
 *
 * **TOML is the documented format**, per Chapter 33 and this package's README,
 * and it is what `friday` writes and looks for. It was chosen there for the
 * reason it usually is: a config file is read by a person more often than by a
 * program, TOML has comments, and JSON does not — a settings file you cannot
 * annotate is one nobody remembers the reasons for.
 *
 * JSON is also accepted, by extension. Not as a second blessed format, but
 * because a file generated by a script or an installer is JSON far more often
 * than it is TOML, and refusing it would buy nothing.
 *
 * Reference: docs/01-bible/33-deployment-strategy.md · docs/adr/0022
 */

/** The file FRIDAY looks for when nobody names one. */
export const DEFAULT_CONFIG_FILENAME = 'config.toml'

/**
 * Finds the configuration file for a data directory.
 *
 * Resolved from the data directory rather than the working directory, so
 * `friday status` behaves the same run from anywhere — a config file that only
 * applies when you are standing in the right folder is a source of "it worked
 * yesterday" that nobody enjoys diagnosing.
 *
 * @param dataDir - The resolved data directory.
 * @returns The path FRIDAY will read if it exists.
 */
export function defaultConfigFile(dataDir: string): string {
  return join(expandPath(dataDir), DEFAULT_CONFIG_FILENAME)
}

/**
 * Reads and parses a configuration file.
 *
 * A missing file is not an error — most installations never have one, and
 * treating its absence as a failure would make the zero-configuration start
 * impossible. A file that exists and cannot be parsed IS an error, because
 * silently ignoring it means running with settings the owner believes they
 * changed. That is the worse of the two failures by a wide margin: it looks
 * like it worked.
 *
 * @param path - The file to read.
 * @returns The parsed layer, an empty layer when the file is absent, or a
 *   typed error naming the file and, where the parser gives one, the line.
 */
export function readConfigFile(path: string): Result<DeepPartialConfig, FridayError> {
  if (!existsSync(path)) return ok({})

  let contents: string
  try {
    contents = readFileSync(path, 'utf8')
  } catch (cause) {
    return err(
      fridayError({
        code: 'CONFIG_UNREADABLE',
        message: `The configuration file at ${path} could not be read.`,
        detail: { path },
        cause,
      }),
    )
  }

  return extname(path).toLowerCase() === '.json'
    ? parseAsJson({ contents, path })
    : parseAsToml({ contents, path })
}

function parseAsToml(input: {
  contents: string
  path: string
}): Result<DeepPartialConfig, FridayError> {
  try {
    return ok(parseToml(input.contents) as DeepPartialConfig)
  } catch (cause) {
    return err(
      fridayError({
        code: 'CONFIG_INVALID',
        // smol-toml's errors name the line and column, which is most of what
        // someone needs to fix the file — so the cause is worth surfacing here
        // rather than only in the detail.
        message: `The configuration file at ${input.path} is not valid TOML. ${describe(cause)}`,
        detail: { path: input.path, format: 'toml' },
        cause,
      }),
    )
  }
}

function parseAsJson(input: {
  contents: string
  path: string
}): Result<DeepPartialConfig, FridayError> {
  try {
    return ok(JSON.parse(input.contents) as DeepPartialConfig)
  } catch (cause) {
    return err(
      fridayError({
        code: 'CONFIG_INVALID',
        message: `The configuration file at ${input.path} is not valid JSON. ${describe(cause)}`,
        detail: { path: input.path, format: 'json' },
        cause,
      }),
    )
  }
}

function describe(cause: unknown): string {
  return cause instanceof Error ? cause.message : ''
}
